# Supported Star Fox 64 Versions: US, JP

09f0d105f476b00efa5303a3ebc42e60a7753b7a:
  name: Star Fox 64 (U) (V1.1) (Compressed)
  preprocess:
    decompress_mio0:
      method: mio0-comptool
      type: decompress
      target: f7475fb11e7e6830f82883412638e8390791ab87
      restart: true

f7475fb11e7e6830f82883412638e8390791ab87:
  name: Star Fox 64 (U) (V1.1)
  path: assets/yaml/us/rev1
  config:
    gbi: F3DEX
    sort: OFFSET
    # logging: ERROR
    output:
      binary: sf64.otr
      code: src/assets
      headers: include/assets
      modding: src/assets
    enums:
      - include/sf64object.h
      - include/sf64level.h
      - include/sf64mesg.h
      - include/sf64audio_external.h
      - include/sf64event.h
      - include/sf64player.h

d064229a32cc05ab85e2381ce07744eb3ffaf530:
  name: Star Fox 64 (JP) (V1.0)
  path: assets/yaml/jp/rev0
  config:
    gbi: F3DEX
    sort: OFFSET
    output:
      binary: mods/sf64jp.otr
      code: src/assets
      headers: include/assets
      modding: src/assets
    enums:
      - include/sf64object.h
      - include/sf64level.h
      - include/sf64mesg.h
      - include/sf64audio_external.h
      - include/sf64event.h
      - include/sf64player.h